---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include ansible-role-packer"
      ansible.builtin.include_role:
        name: "../../../ansible-role-packer/" # noqa: role-name
